Pascalco/harvesttemplates

getcandidates.php, main.js, wpeditionids.json
- added support for Wikispecies, correct input is "species" (lang), "wikimedia" (project)
- fixed bug by loading edition ids for multilingual projects
- fixed typo and added plural support for one message
=> support Wikispecies

main.js
Minor error, instead of checking the value for day (value[2]) there was again a check against the month (value[1]) again, fixed that
=> Fix for day = false

main.js
links to Wikidata items should not escaped
=> fix escaping

main.js
there may be input like "meta:w:" which would point to meta.wikipedia.org
=> Add break after switch

index.php
=> Fix grammar, close HTML tag and add one more news

main.js
indent, alphabetic order, var declaration etc.
=> minor fixes

main.js
uses action=query&meta=siteinfo&siprop=interwikimap
=> make interwiki handling recursive and server-side

main.js
- unused variables, missing var and semicolons, wtih help of JSHint
- rewritten input error detection
=> various fixes

main.js
https://www.wikidata.org/wiki/Q21027105 = quantity property without units
=> handle Q21027105

main.js
- save some jQuery objects
- chain methods
- use data()
- whitespace
=> refactoring

main.js
- eg. "?" wasn't handled correctly
=> use encodeURIComponent() to link pages

getconstraints.php, main.js
- if found, backend now only returns the blacklisted constraint and frontend doesn't load any pages
=> don't allow importing properties under Qualifier or Source only constraints

main.js
- the new alias field was not reachable as the old selector was used
=> fix issue #50

main.js
if loading is pending, you can create another thread which leads to race conditions
=> disable get pages button during loading

main.js
async requests make things a bit harder to handle, will look into it tomorrow, sorry for problems
=> restore all changes from today

main.js
loading should always end with stopLoading() which does the same thing as reportStatus() and re-enables the button
=> disable "get pages" button when loading

main.js
- stopLoading() when siteid is not mapped to an item
- escape template name in one more case
- chain methods
=> refactorings

main.js
- this constraint can also be used to blacklist values of the same property
- improve coding style
=> improve "Conflicts with" constraint

main.js
- there may be multiple thousands separators within a number
- there may be multiple hyphens within a siteid
=> do global replacements

main.js
- properties with 'Conflicts with' which checked itself got never to submitting
=> fix 'Conflicts with'

index.php, main.js
- properties marked as deprecated
- more missing fields
- cleanup
=> don't load in more cases

main.js
- values for 'Unique value' were pushed although they could be rejected by another constraint
- use .done() on all getJSON()'s
- fix URL regex, so that the first url cannot span over another
=> push value on addition, unify Deferred, fix regexes

getconstraints.php, main.js
=> improve Qualifiers constraint

main.js
- when the permalink includes `load=`, the job will start loading when the page is ready
- when the permalink includes `run=`, the job will start running after loading
- disable "get pages" during job
=> make it possible to load and run jobs automatically (#99)

getconstraints.php
see https://www.wikidata.org/wiki/Topic:Tnxgew9id5lwlcn0
=> remove comments from talk page before parsing

main.js
=> add link to the property

main.js
also do not let possible SPARQL errors pass silently
=> fix SPARQL with special characters

main.js
and when the field is emptied, hide the link
=> show template link after form has been prefilled via request

main.js
Remove prefix didn't trim the value.
See also: https://github.com/Pascalco/harvesttemplates/issues/170
=> Fixing minor trim issue
